version: '3.7'


services:
  mysql:
    image: mysql:8.0.12
    container_name: database_dev
    command: mysqld --user=root --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    expose:
      - 3308
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=example
      - MYSQL_ROOT_PASSWORD=root
