server:
  port: 9990
  address: 0.0.0.0
  
debug: false

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3308/test_db?useLegacyDatetimeCode=false&amp&serverTimezone=Europe/Amsterdam&amp&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USER:user}
    password: ${DB_USER:example}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      client:
        access-token-uri: http://0.0.0.0:9990/oauth/token
      resource:
        userInfoUri: http://0.0.0.0:9990/api/v1/auth/me
        