DROP TABLE IF EXISTS ICHAT_UI_SETTING;
DROP TABLE IF EXISTS CHOOSE_CHAT_UI;
DROP TABLE IF EXISTS CHOOSE_LAYOUT;
DROP TABLE IF EXISTS CHAT_LAYOUT;
DROP TABLE IF EXISTS DEMAND_INFO;
DROP TABLE IF EXISTS IAGENT_SERVER;
DROP TABLE IF EXISTS ICHAT_UI;
DROP TABLE IF EXISTS ICHAT_USER;


CREATE TABLE IF NOT EXISTS ICHAT_USER
(
  ID       BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT,
  EMAIL    VARCHAR(128) NOT NULL,
  PASSWORD VARCHAR(64),
  LOCKED   CHAR(1),
  DELETED  CHAR(1),
  CONSTRAINT ICHAT_USER_PK_ID PRIMARY KEY (ID),
  CONSTRAINT ICHAT_USER_UK_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS ICHAT_UI
(
  ID              BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME            VARCHAR(100),
  CONNECTION_TYPE VARCHAR(64) NOT NULL,
  CONSTRAINT ICHAT_UI_PK_ID PRIMARY KEY (ID),
  CONSTRAINT ICHAT_UI_NN_ID CHECK (ID IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS IAGENT_SERVER
(
  ID        BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT,
  ADDRESS   VARCHAR(128) NOT NULL,
  USER_API  VARCHAR(100) NOT NULL,
  PASSWORD  VARCHAR(64),
  CLIENT_ID VARCHAR(128) NOT NULL,
  SECRET    VARCHAR(128) NOT NULL,
  LOCKED    CHAR(1),
  DELETED   CHAR(1),
  CONSTRAINT IAGENT_SERVER_PK_ID PRIMARY KEY (ID),
  CONSTRAINT IAGENT_SERVER_NN_ID CHECK (ID IS NOT NULL),
  CONSTRAINT IAGENT_SERVER_NN_URL CHECK (ADDRESS IS NOT NULL),
  CONSTRAINT IAGENT_SERVER_NN_USER_API CHECK (USER_API IS NOT NULL),
  CONSTRAINT IAGENT_SERVER_NN_CLIENT_ID CHECK (CLIENT_ID IS NOT NULL),
  CONSTRAINT IAGENT_SERVER_NN_SECRET CHECK (SECRET IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS DEMAND_INFO
(
  ID          BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT,
  DEMAND_INFO JSON NOT NULL,

  CONSTRAINT DEMAND_INFO_PK_ID PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CHAT_LAYOUT
(
  ID              BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID         BIGINT (20) UNSIGNED NOT NULL,
  DISPLAY_TYPE    CHAR(1),
  TEXT_INPUT_TYPE CHAR(1),
  BUTTON_TYPE     CHAR(1),
  LOGO            BLOB,
  BACKGROUND_IMG  BLOB,
  BACKGROUND_TYPE CHAR(1),
  FONT_FAMILY     VARCHAR(50),
  FONT_SIZE       SMALLINT,
  FONT_STYLES     BIT(4),
  LOCKED          CHAR(1),
  DELETED         CHAR(1),
  CONSTRAINT CHAT_LAYOUT_PK_ID PRIMARY KEY (ID),
  CONSTRAINT CHAT_LAYOUT_NN_ID CHECK (ID IS NOT NULL)
);


CREATE TABLE IF NOT EXISTS CHOOSE_LAYOUT
(
  USER_ID        BIGINT (20) UNSIGNED NOT NULL,
  CHAT_LAYOUT_ID BIGINT (20) UNSIGNED NOT NULL,
  NAME           VARCHAR(100),
  CONSTRAINT USR_LAYOUT_PK PRIMARY KEY (USER_ID),
  CONSTRAINT USR_LAYOUT_FK_USR_ID FOREIGN KEY (USER_ID) REFERENCES ICHAT_USER (ID),
  CONSTRAINT USR_LAYOUT_FK_CLAYOUT_ID FOREIGN KEY (CHAT_LAYOUT_ID) REFERENCES CHAT_LAYOUT (ID)
);


CREATE TABLE IF NOT EXISTS CHOOSE_CHAT_UI
(
  USER_ID     BIGINT (20) UNSIGNED NOT NULL,
  ICHAT_UI_ID BIGINT (20) UNSIGNED NOT NULL,

  CONSTRAINT USR_CUI_PK_ID PRIMARY KEY (USER_ID, ICHAT_UI_ID),

  CONSTRAINT USR_CUI_FK_USR_ID FOREIGN KEY (USER_ID) REFERENCES ICHAT_USER (ID),
  CONSTRAINT USR_CUI_FK_CUI_ID FOREIGN KEY (ICHAT_UI_ID) REFERENCES ICHAT_UI (ID),

  CONSTRAINT USR_CUI_NN_USR_ID CHECK (USER_ID IS NOT NULL),
  CONSTRAINT USR_CUI_NN_CUI_ID CHECK (C_UI_SETTING_ID IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS ICHAT_UI_SETTING
(
  ICHAT_UI_ID      BIGINT (20) UNSIGNED NOT NULL,
  IAGENT_SERVER_ID BIGINT (20) UNSIGNED,
  CLOUD_ID         BIGINT (20) UNSIGNED,
  URL_PATH         VARCHAR(128) NOT NULL,
  DEMAND_INFO_ID   BIGINT (20) UNSIGNED,

  CONSTRAINT ICHAT_SETTING_FK_ICHAT_ID FOREIGN KEY (ICHAT_UI_ID) REFERENCES ICHAT_UI (ID),
  CONSTRAINT ICHAT_SETTING_FK_IASERVER_ID FOREIGN KEY (IAGENT_SERVER_ID) REFERENCES IAGENT_SERVER (ID),
  CONSTRAINT ICHAT_SETTING_FK_DINFO_ID FOREIGN KEY (DEMAND_INFO_ID) REFERENCES DEMAND_INFO (ID),

  CONSTRAINT ICHAT_SETTING_NN_ICHAT_ID CHECK (ICHAT_UI_ID IS NOT NULL),
  CONSTRAINT ICHAT_SETTING_NN_URL_PATH CHECK (URL_PATH IS NOT NULL),

  CONSTRAINT ICHAT_SETTING_UK_IASERVER_ID UNIQUE (ICHAT_UI_ID, IAGENT_SERVER_ID, URL_PATH, DEMAND_INFO_ID),
  CONSTRAINT ICHAT_SETTING_UK_CLOUD UNIQUE (ICHAT_UI_ID, CLOUD_ID, URL_PATH, DEMAND_INFO_ID)
);


ALTER TABLE ICHAT_USER
AUTO_INCREMENT = 500;

ALTER TABLE ICHAT_UI
AUTO_INCREMENT = 600;

ALTER TABLE IAGENT_SERVER
AUTO_INCREMENT = 700;

ALTER TABLE DEMAND_INFO
AUTO_INCREMENT = 800;

ALTER TABLE CHAT_LAYOUT
AUTO_INCREMENT = 900;